// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
)

const countWalletTransactionsByEmail = `-- name: CountWalletTransactionsByEmail :one
SELECT COUNT(*)
FROM wallet_transactions wt
    JOIN wallets w
        ON wt.wallet_id = w.id
    JOIN players p
        ON w.player_id = p.id
WHERE p.email = $1
`

func (q *Queries) CountWalletTransactionsByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactionsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllWalletTransactionsByEmail = `-- name: GetAllWalletTransactionsByEmail :many
SELECT wt.id, wt.wallet_id, wt.transaction_type, wt.amount, wt.balance_before, wt.balance_after, wt.reference_id, wt.description, wt.created_at
FROM wallet_transactions wt
         JOIN wallets w
              ON wt.wallet_id = w.id
         JOIN players p
              ON w.player_id = p.id
WHERE p.email = $1
ORDER BY wt.created_at DESC
LIMIT $2
OFFSET $3
`

type GetAllWalletTransactionsByEmailParams struct {
	Email  string `json:"email"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetAllWalletTransactionsByEmail(ctx context.Context, arg GetAllWalletTransactionsByEmailParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, getAllWalletTransactionsByEmail, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDemoFaucetTransaction = `-- name: GetDemoFaucetTransaction :one
SELECT id, wallet_id, transaction_type, amount, balance_before, balance_after, reference_id, description, created_at
FROM wallet_transactions
WHERE wallet_id = $1
  AND transaction_type = 'DEMO_FAUCET'
    LIMIT 1
`

func (q *Queries) GetDemoFaucetTransaction(ctx context.Context, walletID int64) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getDemoFaucetTransaction, walletID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionType,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
