// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID        int64              `json:"id"`
	PlayerID  int64              `json:"player_id"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WalletTransaction struct {
	ID              int64              `json:"id"`
	WalletID        int64              `json:"wallet_id"`
	TransactionType string             `json:"transaction_type"`
	Amount          int64              `json:"amount"`
	BalanceBefore   int64              `json:"balance_before"`
	BalanceAfter    int64              `json:"balance_after"`
	ReferenceID     pgtype.Text        `json:"reference_id"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
