// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    username,
    email,
    password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, username, email, password_hash, created_at, updated_at
`

type CreatePlayerParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Username, arg.Email, arg.PasswordHash)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPLayerByEmail = `-- name: GetPLayerByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at
FROM players
WHERE email = $1
`

func (q *Queries) GetPLayerByEmail(ctx context.Context, email string) (Player, error) {
	row := q.db.QueryRow(ctx, getPLayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPLayerByID = `-- name: GetPLayerByID :one
SELECT id, username, email, password_hash, created_at, updated_at
FROM players
WHERE id = $1
`

func (q *Queries) GetPLayerByID(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRow(ctx, getPLayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
