// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	GetPLayerByEmail(ctx context.Context, email string) (Player, error)
	GetPLayerByID(ctx context.Context, id int64) (Player, error)
}

var _ Querier = (*Queries)(nil)
