// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*)
FROM wallet_transactions
WHERE wallet_id = $1
`

func (q *Queries) CountWalletTransactions(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, walletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    player_id,
    balance,
    currency
) VALUES (
    $1, $2, $3
)
RETURNING id, player_id, balance, currency, created_at, updated_at
`

type CreateWalletParams struct {
	PlayerID int64  `json:"player_id"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.PlayerID, arg.Balance, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (
    wallet_id,
    transaction_type,
    amount,
    balance_before,
    balance_after,
    reference_id,
    description
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, wallet_id, transaction_type, amount, balance_before, balance_after, reference_id, description, created_at
`

type CreateWalletTransactionParams struct {
	WalletID        int64       `json:"wallet_id"`
	TransactionType string      `json:"transaction_type"`
	Amount          int64       `json:"amount"`
	BalanceBefore   int64       `json:"balance_before"`
	BalanceAfter    int64       `json:"balance_after"`
	ReferenceID     pgtype.Text `json:"reference_id"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.WalletID,
		arg.TransactionType,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.Description,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionType,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, player_id, balance, currency, created_at, updated_at
FROM wallets
WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByPlayerID = `-- name: GetWalletByPlayerID :one
SELECT id, player_id, balance, currency, created_at, updated_at
FROM wallets
WHERE player_id = $1
`

func (q *Queries) GetWalletByPlayerID(ctx context.Context, playerID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByPlayerID, playerID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, player_id, balance, currency, created_at, updated_at
FROM wallets
WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, transaction_type, amount, balance_before, balance_after, reference_id, description, created_at
FROM wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
    LIMIT $2
OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}


func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets
SET balance = balance + $1
WHERE id = $2
RETURNING id, player_id, balance, currency, created_at, updated_at
`

type UpdateWalletBalanceParams struct {
	Balance int64 `json:"balance"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.Balance, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
